/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddAgentManager: typeof import('./src/components/AgentManager/AddAgentManager.vue')['default']
    AddInsurance: typeof import('./src/components/Insurance/AddInsurance.vue')['default']
    AddManager: typeof import('./src/components/Manager/AddManager.vue')['default']
    AddSponsor: typeof import('./src/components/Sponsor/AddSponsor.vue')['default']
    AgentManagerListTable: typeof import('./src/components/AgentManager/AgentManagerListTable.vue')['default']
    AppTable: typeof import('./src/components/AppTable.vue')['default']
    EditAgentManager: typeof import('./src/components/AgentManager/EditAgentManager.vue')['default']
    EditInsurance: typeof import('./src/components/Insurance/EditInsurance.vue')['default']
    EditManager: typeof import('./src/components/Manager/EditManager.vue')['default']
    EditSponsor: typeof import('./src/components/Sponsor/EditSponsor.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElText: typeof import('element-plus/es')['ElText']
    InsuranceListTable: typeof import('./src/components/Insurance/InsuranceListTable.vue')['default']
    ManagerAvatar: typeof import('./src/components/ManagerAvatar.vue')['default']
    ManagerListTable: typeof import('./src/components/AgentManager/ManagerListTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SponsorListTable: typeof import('./src/components/Sponsor/SponsorListTable.vue')['default']
  }
}
